### ISSUE TITLE
404 Not Found for k8s arm based dashboard

### ISSUE THREAD

**Issue by gleich** [hypriot/blog#104]
Getting a 404 error when trying to run the: 

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-arm.yaml
error: unable to read URL "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-arm.yaml", server reported 404 Not Found, status code=404` 

command in the blog post https://blog.hypriot.com/post/setup-kubernetes-raspberry-pi-cluster/

**Comment by firecyberice** [comment]
Please have a look at the publish date of this blogpost (Wed, Jan 11, 2017).
Of course the ecosystem has evolved since then but it is easy to get a newer version if you follow the link and access e.g. [v1.10.1](https://github.com/kubernetes/dashboard/tree/v1.10.1/src/deploy/recommended) or [v2.0.0](https://github.com/kubernetes/dashboard/tree/v2.0.0-beta8/aio/deploy/recommended).
